instagram/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('user/', include('user.urls', namespace='user')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # all-detail-add-delete-edit
    # fb
    # path('', views.all_posts, name='all_posts'),
    # path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    # path('add_post/<int:user_id>/', views.add_post, name='add_post'),
    # path('post_delete/<int:user_id>/<int:post_id>/', views.post_delete, name='post_delete'),
    # path('post_edit/<int:user_id>/<int:post_id>/', views.post_edit, name='post_edit'),
    # reply
    # path('add_reply/<int:post_id>/<int:comment_id>/', views.add_reply, name='add_reply'),
    # like
    # path('like/<int:post_id>/', views.post_like, name='post_like'),

    # cb
    path('', views.AllPosts.as_view(), name='all_posts'),
    # path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('<str:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('add_post/<int:user_id>/', views.AddPost.as_view(), name='add_post'),
    path('post_delete/<int:user_id>/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    # path('post_delete/<int:user_id>/<int:pk>/', views.PostDeleteGenericView.as_view(), name='post_delete'),
    # path('post_edit/<int:user_id>/<int:post_id>/', views.PostEditView.as_view(), name='post_edit'),
    path('post_edit/<int:user_id>/<int:pk>/', views.PostEditGenericView.as_view(), name='post_edit'),

    # reply
    path('add_reply/<int:post_id>/<int:comment_id>/', views.AddReply.as_view(), name='add_reply'),
    # like
    path('like/<int:post_id>/', views.PostLike.as_view(), name='post_like'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    # fb function base
    # path('login/', views.user_login, name='login'),
    # path('register/', views.user_register, name='register'),
    # path('logout/', views.user_logout, name='logout'),
    # path('dashboard/<int:user_id>/', views.user_dashboard, name='dashboard'),

    # cv
    path('login/', views.UserLogin.as_view(), name="login"),
    path('register/', views.SignUpView.as_view(), name="register"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    # path('profile/', views.CreateProfile.as_view(), name="profile_create"),
    # path('dashboard/<int:user_id>/', views.UserDashboard.as_view(), name='dashboard'),
    # path('dashboard/<int:user_id>/', views.UserDashboard2.as_view(), name='dashboard'),
    path('dashboard/<int:user_id>/', views.UserDashboardPost.as_view(), name='dashboard'),
    path('edit_profile/<int:user_id>/', views.ProfileEditView.as_view(), name='edit_profile'),
    # path('edit_profile/<int:user_id>/', views.ProfileEditGenericView.as_view(), name='edit_profile'),
    # path("edit_profile/<int:pk>/", views.EditProfile2.as_view(), name="edit_profile"),

    # sms
    # path('phone_login/', views.phone_login, name='phone_login'),
    path('phone_login/', views.PhoneLogin.as_view(), name='phone_login'),
    # path('verify/', views.verify, name='verify'),
    path('verify/', views.Verify.as_view(), name='verify'),

    # follow & unfollow
    # path('follow/', views.follow, name='follow'),
    path('follow/', views.Follow.as_view(), name='follow'),
    # path('unfollow/', views.unfollow, name='unfollow'),
    path('follow/', views.UnFollow.as_view(), name='unfollow'),

]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    slug = models.SlugField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[self.slug])

    def likes_count(self):
        return self.pvote.count()

    def user_can_like(self, user):
        user_like = user.uvote.all()
        qs = user_like.filter(post=self)
        if qs.exists():
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomment')
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment {self.body[:30]} by {self.user} '

    class Meta:
        ordering = ('-created',)


class Vote(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvote')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvote')

    def __str__(self):
        return f'{self.user} liked {self.post}'

posts/forms.py
from django import forms
from .models import Post, Comment


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        # fields = ('user','post','body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }
        error_messages = {
            'body': {
                'required': 'این فیلد اجباری است',
            }
        }
        help_texts = {
            'body': 'ماکزیمم 400 کاراکتر'
        }


class AddReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import request
from django.utils.functional import lazy
from .forms import AddPostForm, EditPostForm,AddCommentForm,AddReplyForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.text import slugify
from .models import Post,Comment,Vote
#redis
import redis
from django.conf import settings
# baseview
from django.views import View
# generic
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView,FormView
# mixin
from django.views.generic.edit import FormMixin
# LoginRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin

redis_con = redis.Redis(settings.REDIS_HOST, settings.REDIS_PORT, settings.REDIS_DB)

# Create your views here.
class AllPosts(ListView):
    template_name = 'posts/all_posts.html'
    model = Post
    context_object_name = 'posts' # object_list
    ordering = ['-created']


class PostDetail(FormMixin,DetailView):
    template_name = 'posts/post_detail.html'
    model = Post
    context_object_name = 'post'  # object_list
    slug_field = 'slug' # model field
    slug_url_kwarg = 'slug' # slug name in your url
    form_class = AddCommentForm
    second_form_class = AddReplyForm



    # def get_queryset(self,**kwargs) :
    #     return Post.objects.filter(slug=self.kwargs['slug'])

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', kwargs={'slug': self.kwargs['slug']})


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        slug = self.kwargs['slug']
        # slug = self.kwargs[self.slug_url_kwarg]
        post = get_object_or_404(Post,slug=slug)
        comments = Comment.objects.filter(post=post, is_reply=False)
        context['comments'] = comments
        redis_con.hsetnx('post_views', post.id, 0)
        rviews = redis_con.hincrby('post_views', post.id)
        context['rviews'] = rviews
        context['form'] = AddCommentForm()
        context['reply'] = AddReplyForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        slug = self.kwargs['slug']
        post = get_object_or_404(Post, slug=slug)
        form = form.save(commit=False)
        form.post = post
        form.user = self.request.user
        form.save()
        messages.success(self.request, 'you comment submitted successfully')
        return super().form_valid(form)


    # َAddPost

# AddPost (FormView,CreateView) Ok
class AddPost(LoginRequiredMixin, FormView):
    template_name = 'posts/add_post.html'
    form_class = AddPostForm

    # success_url = reverse_lazy('user:dashboard')

    def get_success_url(self, **kwargs):
        return reverse_lazy('user:dashboard', kwargs={'user_id': self.request.user.id})

    # if request.user.id == user_id:
    def form_valid(self, form):
        if self.request.user.id == self.kwargs['user_id']:
            self.add_post(form.cleaned_data)
            return super().form_valid(form)

    def add_post(self, data):
        new_post = Post(user=self.request.user, body=data['body'], slug=slugify(data['body'][:30]))
        new_post.save()
        messages.success(self.request, 'your post submitted', 'success')

# CreateView(ok)
class AddPostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['body']
    template_name = 'posts/add_post.html'

    # form_class = AddPostForm
    # success_url = reverse_lazy('user:dashboard')

    def get_success_url(self, **kwargs):
        return reverse_lazy('user:dashboard', kwargs={'user_id': self.request.user.id})

    # if request.user.id == user_id:
    def form_valid(self, form):
        if self.request.user.id == self.kwargs['user_id']:
            new_post = form.save(commit=False)
            new_post.user = self.request.user
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(self.request, 'your post submitted', 'success')
            return super().form_valid(form)

#PostDelete (ok)
class PostDeleteView(LoginRequiredMixin,View):

    def post(self,request, user_id, post_id):
        if self.request.user.id == self.kwargs['user_id']:
            # Post.objects.filter(pk=post_id).delete()
            p = Post.objects.filter(pk=post_id)
            p.delete()
            messages.success(request, 'your post deleted successfully', 'success')
            return redirect('user:dashboard', user_id)

# DeleteView(ok)
class PostDeleteGenericView(LoginRequiredMixin, DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    # success_url ="/"

    def get_success_url(self, **kwargs):
        return reverse_lazy('user:dashboard', kwargs={'user_id': self.request.user.id})

    def post(self, request, user_id, post_id):
        if self.request.user.id == self.kwargs['user_id']:
            messages.success(request, 'your post deleted successfully', 'success')
            return super().post(request)
        else:
            # return "you dont delete this post"
            messages.error(request, 'your dont  deleted this post', 'error')
            return redirect('user:dashboard', user_id)

# edit(ok)
class PostEditView(LoginRequiredMixin,View):
    # if self.request.user.id == self.user_id:
    def get_object(self,post_id):
        post = get_object_or_404(Post, pk=post_id)
        return post

    def get(self, request,user_id, post_id):
        if self.request.user.id == self.kwargs['user_id']:
            form = EditPostForm(instance=self.get_object(post_id))
            return render(request, "posts/edit_post.html", {"form": form})
        else:
            return redirect('posts:all_posts')

    def post(self,request,user_id, post_id):
        if self.request.user.id == self.kwargs['user_id']:
            form = EditPostForm(request.POST, instance=self.get_object(post_id))
            if form.is_valid():
                ep = form.save(commit=False)
				# change body =>change slug
                ep.slug = slugify(form.cleaned_data['body'][:30])
                ep.save()
                messages.success(request, 'your post edited successfully', 'success')
                return redirect('user:dashboard', user_id)
            return render(request, "posts/edit_post.html", {"form": form})
        else:
            return redirect('posts:all_posts')

# UpdateView(ok)
class PostEditGenericView(LoginRequiredMixin,UpdateView):
    form_class = EditPostForm
    template_name = "posts/edit_post.html"
    model = Post

    def get_success_url(self,**kwargs):
        return reverse_lazy('user:dashboard',kwargs = { 'user_id': self.request.user.id})

    def get_context_data(self, **kwargs):
        form = EditPostForm(instance=self.get_object())
        context = {'form': form}
        return context

# reply(ok)
class AddReply(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'posts/post_detail.html'
    form_class = AddReplyForm
    # success_url = reverse_lazy('user:dashboard ')

    def form_valid(self, form):
        form.instance =form.save(commit=False)
        form.instance.user = self.request.user
        # post = Post.objects.get(id=self.kwargs['post_id'])
        post = get_object_or_404(Post,id=self.kwargs['post_id'])
        form.instance.post = post
        # comment = Comment.objects.get(pk=self.kwargs['comment_id'])
        comment = get_object_or_404(Comment, pk=self.kwargs['comment_id'])
        form.instance.reply = comment
        form.instance.is_reply=True
        form.instance.save()
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        messages.success(self.request, 'your reply for this comment  submitted', 'success')
        post = Post.objects.get(pcomment=self.kwargs['comment_id'])
        return post.get_absolute_url()

# like(Ok)
class PostLike(LoginRequiredMixin,View):
    def get(self,request,post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote(post=post, user=request.user)
        like.save()
        messages.success(request, 'you liked successfully', 'success')
        return redirect('posts:post_detail', post.slug)

posts/templates/posts/add_post.html
{% extends 'base.html' %}

{% block title %} {{ request.user.username }} add post {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Post" class="btn btn-primary">
    </form>
{% endblock %}

posts/templates/posts/all_posts.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
    {% for post in posts %}
        <div class="card">
            <p class="card-header"><a href="{% url 'user:dashboard' post.user.id %}">{{ post.user }}</a></p>
            <p class="card-body"><a href="{{ post.get_absolute_url }}">{{ post.body }}</a></p>
        </div><br/>
    {% endfor %}
{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %} Edit Post {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit" class="btn btn-primary">
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content %}
<!-- <p class="card-header">{{ post.user }}</p>-->
    <p>{{ post.user }} | {{ post.created|date }} | {{ rviews }} views</p>
    <p>{{ post.body }}</p><hr/>
<!-- like  & unlike -->
{% if request.user.is_authenticated %}
    <a href="{% url 'posts:post_like' post.id %}" class="mb-5 btn btn-primary {% if can_like %}disabled {% endif %} col-md-2">Like {{ post.likes_count }}</a>
{% endif %}

<!-- number of comment -->
    {% with total=comments.count %}
        <p>This post has {{ total }} comment{{ total|pluralize }}</p>
    {% endwith %}
<!-- delete & edit post in detail's post -->
    {% if request.user.is_authenticated and request.user.id == post.user.id%}
    <div class="row">
         <form action="{% url 'posts:post_delete' post.user.id post.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-danger">Delete post</button>
            </form>
           <br>
        <a class ="btn btn-secondary ml-2"href="{% url 'posts:post_edit' post.user.id post.id %}">Edit post</a>
    </div>
    {% endif %}
        <!-- form AddCommentForm mixin in detail view -->
    {% if request.user.is_authenticated %}
    <form action="" method="post" novalidate class="col-md-6">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send" class="btn btn-primary">
    </form>
    {% else %}
        <p>only logged in users can send comments</p>
    {% endif %}<br/><br/><br/>
<!--showing comments-->
<!--    {% for comment in comments %}-->
<!--			<div class="card bg-dark text-white">-->
<!--				<p class="card-header">{{ comment.user }}</p>-->
<!--				<p class="card-body">{{ comment.body }}</p>-->
<!--            </div>-->
<!--    {% empty %}-->
<!--        <p>There is no comment</p>-->
<!--    {% endfor %}-->
<!--showing comment and replies-->
{% for comment in comments %}
		{% if not comment.reply %}
			<div class="card bg-dark text-white">
				<p class="card-header">{{ comment.user }}</p>
				<p class="card-body">{{ comment.body }}</p>
				<!-- showing form replies -->
				{% if request.user.is_authenticated %}
				<div class="card-body">
					<form action="{% url 'posts:add_reply' post.id comment.id %}" method="post">
						{% csrf_token %}
						{{ reply.as_p }}
						<input type="submit" value="Send">
					</form>
				</div>
				{% else %}
					<p>you have to login to send reply</p>
				{% endif %}
				<!-- showing replies -->
                <!--backward relation(comment & reply) reply's related_name is rcomment-->
				{% for reply in comment.rcomment.all %}
					<p class="bg-primary text-white p-3 m-5">{{ reply.user }} <br/> {{ reply.body }}</p>
				{% endfor %}
			</div><br/>
		{% endif %}
    {% empty %}
        <p>There is no comment</p>
    {% endfor %}
{% endblock %}